from datetime import date

product1 = Product(name='OnePlus 11', description='A sleek, high-performance smartphone with Snapdragon 8 Gen 2 and triple-camera setup.', price=1200, cpu='Snapdragon 8 Gen 2', gpu='Adreno 740', camera='50MP + 48MP + 32MP', battery='5000mAh', release_date=date(2023, 2, 7), image='oneplus.webp', brand_name='OnePlus')
product2 = Product(name='Sony Xperia 1 V', description='Sony’s flagship with 4K OLED display and pro-grade Alpha camera.', price=1400, cpu='Snapdragon 8 Gen 2', gpu='Adreno 740', camera='48MP + 12MP + 12MP', battery='5000mAh', release_date=date(2023, 6, 10), image='experia.webp', brand_name='Sony')
product3 = Product(name='Huawei Mate 50 Pro', description='The premium Huawei phone with a top-notch camera and a powerful battery.', price=1300, cpu='Kirin 9000', gpu='Mali-G78', camera='50MP + 12MP + 20MP', battery='4700mAh', release_date=date(2022, 10, 25), image='mate_50_pro.webp', brand_name='Huawei')
product4 = Product(name='Xiaomi 13 Ultra', description='Flagship phone with Snapdragon 8 Gen 2, Leica cameras, and advanced cooling technology.', price=1100, cpu='Snapdragon 8 Gen 2', gpu='Adreno 740', camera='50MP + 48MP + 48MP', battery='5000mAh', release_date=date(2023, 4, 19), image='xiaomi_13_ultra.webp', brand_name='Xiaomi')
product5 = Product(name='Oppo Find X6 Pro', description='High-end device with premium display, powerful chipset, and a versatile camera system.', price=1150, cpu='Dimensity 9200', gpu='Immortalis-G715', camera='50MP + 50MP + 32MP', battery='5000mAh', release_date=date(2023, 3, 22), image='find_x6_pro.webp', brand_name='Oppo')
product6 = Product(name='Asus ROG Phone 7', description='Ultimate gaming phone with Snapdragon 8 Gen 2, 165Hz AMOLED display, and AirTrigger controls.', price=1400, cpu='Snapdragon 8 Gen 2', gpu='Adreno 740', camera='50MP + 13MP', battery='6000mAh', release_date=date(2023, 5, 5), image='rog_phone_7.webp', brand_name='Asus')
product7 = Product(name='Motorola Edge 40 Pro', description='Flagship phone with ultra-fast charging, Snapdragon 8 Gen 2, and curved display.', price=1000, cpu='Snapdragon 8 Gen 2', gpu='Adreno 740', camera='50MP + 12MP + 50MP', battery='4600mAh', release_date=date(2023, 4, 15), image='edge_40_pro.webp', brand_name='Motorola')
product8 = Product(name='Apple iPhone 18', description='Latest iPhone with A18 Bionic chip, advanced camera system, and longer battery life.', price=2000, cpu='Apple A18 Bionic', gpu='Apple-designed', camera='48MP + 12MP + 12MP', battery='4000mAh', release_date=date(2023, 9, 20), image='iphone_18.webp', brand_name='Apple')
product9 = Product(name='Google Pixel 8 Pro', description='The latest Google Pixel with revolutionary AI camera and enhanced security features.', price=1500, cpu='Google Tensor G3', gpu='Mali-G710', camera='48MP + 12MP + 12MP', battery='5000mAh', release_date=date(2023, 10, 1), image='pixel_8_pro.webp', brand_name='Google')
product10 = Product(name='Samsung Galaxy S23 Ultra', description='Samsung’s high-end smartphone with a 200MP camera and a powerful Snapdragon processor.', price=1800, cpu='Snapdragon 8 Gen 2', gpu='Adreno 740', camera='200MP + 12MP + 10MP', battery='5000mAh', release_date=date(2023, 2, 17), image='galaxy_s23_ultra.webp', brand_name='Samsung')
